# 通配符 ** 表示任意级的目录
mybatis:
  mapper-locations: cn.hhu.xy.dao.**.*Dao.xml
  type-aliases-package: .cn.hhu.xy.bean

spring:
  datasource:
    # druid配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://121.248.201.91:3306/xy_mybatis
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: sdb3309
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      poolPreparedStatements: true
      #开启poolPreparedStatements后生效
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      # stat：监控统计，wall：防御sql注入，log4j2：日志记录
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      stat-view-servlet:
        login-username: xy
        login-password: xy
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      # 数据库连接不上，重连的时间：1h 测试后无效
      break-after-acquire-failure: true
      time-between-connect-error-millis: 3600000